### ISSUE TITLE
[code]Ajout de l'inscription aux tournois automatique

### ISSUE THREAD

**Issue by rgambard** [tagadanar/leekwars_gardener#1]
Voila voila je ne savais pas trop où le poster mais si ca peut aider quelqu'un :) D'ailleurs merci beaucoup tagadanar pour ton partage !
lwapi.py
```python
       def register_tournaments(self):
                r = self.s.post("%s/farmer/register-tournament"%self.rooturl)
                for leekid, leekinfo in self.farmer['leeks'].items():
                        r = self.s.post("%s/leek/register-tournament"%self.rooturl, data={'leek_id':leekid})
                        if r:
                                print(leekinfo["name"], "registred to tournament")
```

**Comment by tagadanar** [comment]
merci pour ça, je comptais l'ajouter un de ces 4 :)

je vais l'intégrer à mon code pour que ça soit configurable par leek et par compte selon les besoins

**Comment by rgambard** [comment]
Avec plaisir, à bientôt dans le potager ! (plus que 290 levels et 3 poireaux pfiou)

**Comment by tagadanar** [comment]
je ferme l'issue, j'ajoute la modif à mon script dans l'aprem, avec les indications dans le readme pour la config
encore merci de ta contribution :)

edit : à noter que j'ai changé les noms des globals FARMER et LEEK_X, les _ étaient useless, du coup gaffe à ta config dans settings
